### ISSUE TITLE
Ładne przeprosiny jak brak danych

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/ParlData-Widgets#4]
Gdy zapytanie zwróci 404
`http://api.parldata.eu/sk/nrsr/people/54ca98d1273a3904ff8b2828?embed=[%22memberships.organization%22] 404 (NOT FOUND)`

To wyświetlać: `Missing data, please <a href="http://parldata.eu/?page_id=783">check scrapers status.</a>` I nad tym może dużą czcionnką 404 wycentrowane.

**Comment by debarbaro** [comment]
?

W dniu czwartek, 5 lutego 2015 Krzysiek Madejski <notifications@github.com>
napisał(a):

> Gdy zapytanie zwróci 404
>
> http://api.parldata.eu/sk/nrsr/people/54ca98d1273a3904ff8b2828?embed=[%22memberships.organization%22]
> 404 (NOT FOUND)
>
> To wyświetlać: Missing data, please <a href="
> http://parldata.eu/?page_id=783">check scrapers status.</a> I nad tym
> może dużą czcionnką 404 wycentrowane.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/ParlData-Widgets/issues/4>.
>


-- 
Sent from Gmail Mobile
